export const homeObj = {
    id : 'about',
    lightBg: false,
    lightText: true,
    lightTestDesc: true,
    topLine:'My Experience is:',
    headline: 'Web Developer',
    description: 'With more that 5 year of development web intefaces and backends',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/logo-js.png'),
    alt: 'car',
    dark: true,
    primary: true,
    darkText: true,
};
export const homeObj2 = {
    id : 'experience',
    lightBg: true,
    lightText: false,
    lightTestDesc: false,
    topLine:'My Experience is:',
    headline: 'Web Developer',
    description: 'With more that 5 year of development web intefaces and backends',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../images/logo-js.png'),
    alt: 'car',
    dark: false,
    primary: false,
    darkText: false,
};