export const homeObj = {
    id : 'About',
    lightBg: false,
    lightText: true,
    lightTestDesc: true,
    topLine:'About Me:',
    headline: 'Software Engineer',
    description: 'I am a passionate developer with more than 8 years of experience. I\'ve been involved in every step of software and web development. As a software engineer my goal is to always build applications that are scalable and efficient under the hood while providing engaging and dynamic user experiences.',
    description2: 'When Im not in front of a computer screen, I\'m probably taking photos, cruising around on my penny board, or crossing off another item on my bucket list.',
    buttonLabel: '',
    imgStart: false,
    img: require('../../images/me.jpg'),
    alt: 'car',
    dark: true,
    primary: true,
    darkText: true,
};