export const homeObj = {
    id : 'about',
    lightBg: false,
    lightText: true,
    lightTestDesc: true,
    topLine:'Full Stack Web Developer',
    headline: 'Web Developer',
    description: 'With more that 5 year of development web interfaces and backends usign up to date skills and technologies',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/me.jpg'),
    alt: 'car',
    dark: true,
    primary: true,
    darkText: true,
};
export const homeObj2 = {
    id : 'experience',
    lightBg: false,
    lightText: true,
    lightTestDesc: true,
    topLine:'Selenium and Web QA Development',
    headline: 'QA Automation Developer',
    description: 'I\'ve realized many bots that realize thorough test on new implementations.',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../images/logo-js.png'),
    alt: 'car',
    dark: true,
    primary: false,
    darkText: true,
};